version: "3.8"
services:
  db:
    image: "postgres:11.11"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: "redis:6-alpine"
    expose:
      - "6379"
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      target: api
    depends_on:
      db:
        condition: service_healthy

    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - UVICORN_LOG_LEVEL=debug
    restart: unless-stopped
    volumes:
      - .:/opt/app
    expose:
      - "8090"
    ports:
      - "8090:8090"

  worker:
    build:
      context: .
      target: worker
    command: ["worker_with_beat"]
    depends_on:
      - db
      - cache
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - CELERY_LOG_LEVEL=INFO
    restart: unless-stopped
    volumes:
      - .:/opt/app
